fuimos:
  services:
    interaction: http://localhost:${micronaut.server.port}/fuimos/interaction
    message: http://localhost:${micronaut.server.port}/fuimos/message
micronaut:
  server:
    port: 9090
  metrics:
    export:
      cloudwatch:
        enabled: false
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  security:
    authentication: idtoken
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
otel:
  traces:
    exporter: otlp,jaeger,logging
    propagator: tracecontext, baggage, xray
  exclusions:
    - /health
netty:
  default:
    allocator:
      max-order: 3
mongodb:
  uri: mongodb://pcc:123456789@localhost:27017/fuimos
